### ISSUE TITLE
Using fonts, images, etc in local directory

### ISSUE THREAD

**Issue by simakwm** [curityio/example-consentor#1]
Hello! 

Is it possible to load fonts, css or images located in the template index directory?

**Comment by mtrojanowski** [comment]
Hi @simakwm!

It's not possible to load them directly from the template directory, but you can put any fonts, CSS, and images in the `$IDSVR_HOME/usr/share/webroot/` directory. All files in this directory are exposed by the server. You can then include them in your templates. For example, if you put `logo.png` file in the `webroot` folder, you can then include it in a template:

```html
<img alt="logo" src="/logo.png" />
```

If you need to change the theme that your plugin will be using it might be simpler to use the same classes that are used by other Curity Identity Server templates and change the theme globally with the [Look and Feel](https://curity.io/resources/learn/customize-look-and-feel-simple/) editor.

**Comment by simakwm** [comment]
Thanks Michal!
I am not going to use default templates.
I was told there is a way to achieve that creating a handler for those static files, but this seems simpler for me =)

**Comment by mtrojanowski** [comment]
Hey @simakwm, this can actually be achieved with files kept with the plugin code. You can create a `webroot` folder under `src/main/resources` in your plugin. The Curity Identity Server will automatically expose any files in this folder. So you don't have to copy anything to `$IDSVR_HOME/usr/share/webroot/`. You can keep all the static files in your plugin's jar.

**Comment by simakwm** [comment]
Awesome! Will they be accessible from "/" as well?

**Comment by mtrojanowski** [comment]
Exactly.
